language: ruby
script: bundle exec rake test

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-4.0-stable
  - gemfiles/Gemfile.rails-3.2-stable
  - gemfiles/Gemfile.rails-head

matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.rails-head

